replicaCount: 1

deployment:
  image:
    repository: quay.io/go-skynet/local-ai
    tag: master-ffmpeg-core
  env:
    threads: 4
    context_size: 512
    debug: "True"
  modelsPath: "/models"

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Prompt templates to include
# Note: the keys of this map will be the names of the prompt template files
promptTemplates:
  {}

# Models to download at runtime
models:
  forceDownload: false

  list:
    #-  url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"
    #- url: "http://192.168.0.71/stable-code-3b-q4_k_m.gguf"
      # basicAuth: base64EncodedCredentials

persistence:
  models: 
    enabled: true
    annotations: {}
    storageClass: standard
    accessModes: ReadWriteOnce
    size: 10Gi
    globalMount: /models
  output:
    enabled: true
    annotations: {}
    storageClass: standard
    accessModes: ReadWriteOnce
    size: 5Gi
    globalMount: /tmp/generated

service:
  type: ClusterIP
  port: 80
  annotations: {}

ingress:
  enabled: false

nodeSelector:
  kubernetes.io/hostname: "kind-worker2"

tolerations: []

affinity: {}


